# Deployment

replicaCount: 2

terminationGracePeriodSeconds: 120 # synchronisée avec deregistration_delay (ALB)

image:
  repository: ghcr.io/naqa92/todolist
  tag: "0.1.3"
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"

env: {}

env_secrets:
  - name: DATABASE_URL
    secretName: "db-app"
    secretKey: "uri"

port: 5000

readinessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 5
  timeoutSeconds: 5

livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 30
  timeoutSeconds: 5

startupProbe: {}

lifecycle:
  preStop:
    exec:
      command: ["/bin/sh", "-c", "sleep 15"] # Délai avant SIGTERM pour finir les requêtes en cours

# Service

service:
  enabled: true
  type: ClusterIP
  port: 5000
  targetPort: 5000

# Ingress

ingress:
  enabled: true
  className: "nginx" # local: nginx / EKS: alb
  host: todolist.127.0.0.1.nip.io
  annotations: {}
  # alb.ingress.kubernetes.io/scheme: internet-facing
  # alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443},{"HTTP":80}]'
  # alb.ingress.kubernetes.io/ssl-redirect: "443"
  # external-dns.alpha.kubernetes.io/hostname: app.ndebaa.com
  # cert-manager.io/cluster-issuer: "letsencrypt"
  # cert-manager.io/secret-template: |
  # {"annotations": {"cert-manager-sync.lestak.sh/sync-enabled":"true", "cert-manager-sync.lestak.sh/acm-enabled":"true", "cert-manager-sync.lestak.sh/acm-region": "eu-west-3"}}
  tls: []
  # - hosts:
  #     - app.ndebaa.com
  #   secretName: letsencrypt-app
