{{- $root := . }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $root.Release.Name }}
  namespace: {{ $root.Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $root.Release.Name }}
spec:
  replicas: {{ $root.Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $root.Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $root.Release.Name }}
    spec:
{{- if $root.Values.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ $root.Values.terminationGracePeriodSeconds }}
{{- end }}
      containers:
        - name: {{ $root.Release.Name }}
          image: "{{ $root.Values.image.repository }}:{{ $root.Values.image.tag }}"
          imagePullPolicy: {{ $root.Values.image.pullPolicy }}
{{- if $root.Values.port }}
          ports:
            - name: http
              containerPort: {{ $root.Values.port }}
{{- end }}
{{- if or $root.Values.env $root.Values.env_secrets }}
          env:
{{- range $root.Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
{{- end }}
{{- range $root.Values.env_secrets }}
            - name: {{ .name }}
              valueFrom:
                secretKeyRef:
                  name: {{ .secretName }}
                  key: {{ .secretKey }}
{{- end }}
{{- end }}
{{- with .Values.livenessProbe }}
          livenessProbe:
{{ toYaml . | nindent 12 }}
{{- end }}
{{- with .Values.readinessProbe }}
          readinessProbe:
{{ toYaml . | nindent 12 }}
{{- end }}
{{- with .Values.startupProbe }}
          startupProbe:
{{ toYaml . | nindent 12 }}
{{- end }}
{{- with .Values.lifecycle }}
          lifecycle:
{{ toYaml . | nindent 12 }}
{{- end }}
{{- with .Values.resources }}
          resources:
{{ toYaml . | nindent 12 }}
{{- end }}