{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | nindent 4 }}
{{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
{{- with .Values.ingress.tls }}
  tls:
{{ toYaml . | nindent 4 }}
{{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Release.Name }}
                port:
                  number: {{ .Values.service.port }}
            path: /
            pathType: ImplementationSpecific # Laisse le contrôleur décider entre Prefix et Exact
{{- end }}